### ISSUE TITLE
Unable to install package

### ISSUE THREAD

**Issue by dev-awevo** [mirakl/magento2-seller-connector#1]
Hi,

It's impossible to install the package using the following command (https://github.com/mirakl/magento2-seller-connector#installing-the-connector):
`composer require mirakl/connector-magento2-seller`

 > [InvalidArgumentException]
>   Could not find a matching version of package mirakl/connector-magento2-seller. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability (stable).

But possible with the following command: 
`composer require mirakl/magento2-seller-connector`

**What installation method to keep ?**

Regards

**Comment by jreinke** [comment]
Hello,

You are right, there is a typo in the installation manual.
The valid package name is: `mirakl/magento2-seller-connector`

Thank you.

Johann
