### ISSUE TITLE
problem listing mirakl magento

### ISSUE THREAD

**Issue by ExacomptaUser75** [mirakl/magento2-seller-connector#24]
Hi,

A customer has disabled his marketplace, so when I try to access the list of my marketplaces I get this error.

![problem-2](https://github.com/mirakl/magento2-seller-connector/assets/146961863/11a6f53b-96dc-42a2-8679-121fd1f6593c)

![problem-mirakl](https://github.com/mirakl/magento2-seller-connector/assets/146961863/b5593d26-f9f8-4896-a1ca-a7a12dd9f4b4)

As a result, not only can I not access my other marketplace listings.

My customer has temporarily disabled his marketplace.

Do you have a patch to avoid this kind of problem?

Thank you,

**Comment by jreinke** [comment]
Hello,

Thanks for your feedback, we are going to verify the issue and provide a potential fix.

**Comment by ExacomptaUser75** [comment]
Hi,

Thank you for your reply.

**Comment by jreinke** [comment]
Fixed since v1.7.7
