### ISSUE TITLE
what category to send mirakl in magento 2

### ISSUE THREAD

**Issue by ExacomptaUser75** [mirakl/magento2-seller-connector#27]
Hello,

How to select the category that will be mapped on mirakl if the product has two categories in magento 2.

Thanks for your feedback.

**Comment by jreinke** [comment]
Hello,

The default behavior of the connector is:
- take the deepest category
- if several categories have the same level, take the first one alphabetically

Best regards.

**Comment by ExacomptaUser75** [comment]
Hi thank you,

Best regards,
