### ISSUE TITLE
Extend variants_attributes size for stores with many configurable attribute

### ISSUE THREAD

**Issue by dsonnet** [mirakl/magento2-seller-connector#3]
variants_attributes is set to 255 chars, if you try to store a long list of excluded attributes you will end up with Json Unable to unserialize value. Error: Control character error, possibly incorrectly encoded

**Comment by jreinke** [comment]
Hello,

Sorry for the late reply but this bug has been fixed since [v1.2.4](https://github.com/mirakl/magento2-seller-connector/releases/tag/v1.2.4).

Thank you.
