### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by simonmaass** [mirakl/magento2-seller-connector#31]
There are a lot of issues from 2-3 years ago... Is this still maintained?

**Comment by JPGrandclementMirakl** [comment]
Hello,
Thanks for reaching out!

We recently released the new Mirakl Magento Connect Connector that enables you to integrate your Magento store with all our marketplaces via our platform Mirakl Connect.
Please note that starting in H2 2024, there will no longer be any support from our support teams as well as any updates of our previous Magento 2 connector.

You can find the detailed documentation of our new connector here: https://help.mirakl.net/bundle/sellers/page/topics/Connectors/Magento_seller/mg_seller_connector.html

The first step to use our new Mirakl-Magento Connector is to create your account in Mirakl Connect. To do so you need to complete the form to register here :  [link](https://account.mirakl.net/signup/external?sign=o0OPIQ-qIq0%3D.M_hEuULHftddn5tqENN72BpCb8kEG4vInzXXXAAqlg0%3D&organization_selector=true&callback=https%3A%2F%2Fmiraklconnect.com%2Fregistration%2Fseller%2Ffinalize&create_organization=true&type=SHOP&product_id=CONNECT).
Once done, you should receive a confirmation email with the subject "Join Mirakl Connect". You then need to click on the invitation link, and you should be able to log in.

After you are logged in, any questions regarding the Magento Connector will need to go through our support platform on Mirakl Connect. Please submit a ticket to the team by logging into your Mirakl Connect account and clicking on Contact Us in the bottom left corner. To provide the best seller support possible we’ve developed a platform for this sole purpose and won’t be able to get back to you via email.

Thanks for your understanding!

Regards,
JP
