### ISSUE TITLE
Import order is verly slow

### ISSUE THREAD

**Issue by yacine123bain** [mirakl/magento2-seller-connector#8]
Hi,
I have installed the module successfully and able to setup it up.
Now, when I tried to import one order, it take a lot of time (15 mins) which is very long..
Could you tell me if its normal ?
FYI, I have tried to import 2 orders coming from 2 differents Marketplaces

Thanks

**Comment by jreinke** [comment]
Hello,

Of course it's not normal, it can take several seconds but not several minutes.
You should debug this manually in your Magento environment I think because this is not something we are reproducing locally.

Best,

Johann
